In [17]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [4]:
import numpy as np
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)
type(numpy_array)

[1 2 3 4 5]


numpy.ndarray

In [22]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [23]:
a.shape

(6,)

In [69]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [70]:
b.size

6

In [46]:
c = np.array([(1,2.2,3,4,5),(5,8,3,9,23),(0,0,0,0,0),(4,0,5,4,3)],dtype=float)
print(c)

[[ 1.   2.2  3.   4.   5. ]
 [ 5.   8.   3.   9.  23. ]
 [ 0.   0.   0.   0.   0. ]
 [ 4.   0.   5.   4.   3. ]]


In [47]:
c.shape

(4, 5)

In [49]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [51]:
x.size

20

In [65]:
y = np.ones((4,3,3,3))
print(y)

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]


In [67]:
z = np.full((4,3),7)
print(z)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [68]:
I = np.eye(6)
print(I)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [71]:
# For random Values
b = np.random.random((3,4))
print(b)                  # Values will be between 0 and 1 

[[0.82519288 0.54419215 0.28782974 0.03379075]
 [0.67957149 0.12126958 0.25305389 0.13779993]
 [0.96351248 0.23460229 0.16049738 0.79881043]]


In [74]:
# For random Values Array within a specific range
c = np.random.randint(5,109,(4,5))
print(c)

[[ 60  39  27  13  18]
 [ 95  72  59  23  35]
 [ 77  77  98  18 104]
 [ 92  83  28 108  65]]


In [76]:
c = np.random.randint(5,109,(2,4,4,5))
print(c)

[[[[ 12  23  28  96  48]
   [ 65  10  85  88  41]
   [ 85  88  63  36 101]
   [ 10  49  74  15  51]]

  [[ 34  31  15  39  99]
   [ 74 108  38  15 103]
   [ 66  60  13  34  12]
   [ 35  72  18  45  25]]

  [[105  52  48  64  49]
   [ 93  90  67  33  15]
   [ 52  51  92  39 100]
   [ 10  86 105  74  31]]

  [[ 82  75 107  82  62]
   [ 85  21  35  30  13]
   [  5  50  51  26  26]
   [ 69  47  45  74  48]]]


 [[[ 33  14  13  83  79]
   [ 19 105  61 106  17]
   [ 40  89  13  13  27]
   [ 76  60  85  75  12]]

  [[ 45  41 108  35  46]
   [ 66  78  99  42  34]
   [107  12  92  51 105]
   [ 32  70  11  74  57]]

  [[ 92  77  72 108  12]
   [ 27  54  17 102  71]
   [ 36  41  72  69  69]
   [ 74  42  64  48  66]]

  [[ 54   7  13  65 100]
   [107  83  80 100  91]
   [ 68  12  14  73  43]
   [ 91  56 103  21  83]]]]


In [78]:
# Array of evenly spaced values --> Specifying the number of values
d = np.linspace(0,40,5)
print(d)

[ 0. 10. 20. 30. 40.]


In [79]:
# Array of evenly spaced values --> Specifying the step
e = np.arange(10,40,4)
print(e)

[10 14 18 22 26 30 34 38]


In [81]:
# To convert a list to a numpy array
list2 = [20,9,4,7,13]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[20  9  4  7 13]


numpy.ndarray

In [89]:
tuple1 = (2,45,90,'Ass')
print(tuple1)
print(type(tuple1))

(2, 45, 90, 'Ass')
<class 'tuple'>


In [91]:
array1 = np.asarray(tuple1)
print(array1)
print(type(array1))

['2' '45' '90' 'Ass']
<class 'numpy.ndarray'>


In [97]:
k = np.random.randint(10,90,(5,5))
print(k)

[[83 47 34 17 19]
 [76 13 61 75 42]
 [79 81 20 69 61]
 [34 79 89 81 49]
 [34 15 76 30 66]]


In [93]:
# Array Dimension:
print(k.shape)

(5, 5)


In [94]:
# Number of dimension:
print(k.ndim)

2


In [95]:
# Number of elements:
print(k.size)

25


In [98]:
# Checking the datatype of elements in the array:
print(k.dtype)

int32


In [103]:
# Two list just concatenate instead of addition after doing add operation
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)
type(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


list

In [127]:
a = np.array([(1,2,3),(4,5,6),(1,2,3)])
b = np.array([(1,2,9),(3,5,16),(1,2,3)])
print(a,"\n\n", b)


[[1 2 3]
 [4 5 6]
 [1 2 3]] 

 [[ 1  2  9]
 [ 3  5 16]
 [ 1  2  3]]


In [128]:
print(a+b)

[[ 2  4 12]
 [ 7 10 22]
 [ 2  4  6]]


In [129]:
print(a-b)

[[  0   0  -6]
 [  1   0 -10]
 [  0   0   0]]


In [130]:
print(a*b)

[[ 1  4 27]
 [12 25 96]
 [ 1  4  9]]


In [131]:
print(a/b)

[[1.         1.         0.33333333]
 [1.33333333 1.         0.375     ]
 [1.         1.         1.        ]]


In [132]:
print(np.add(a,b))

[[ 2  4 12]
 [ 7 10 22]
 [ 2  4  6]]


In [133]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[  0   0  -6]
 [  1   0 -10]
 [  0   0   0]]
[[ 1  4 27]
 [12 25 96]
 [ 1  4  9]]
[[1.         1.         0.33333333]
 [1.33333333 1.         0.375     ]
 [1.         1.         1.        ]]


# Array Manipulation

In [135]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 9 1]
 [7 7 2]]
(2, 3)


In [136]:
# Transpose of Matrix

In [138]:
trans = np.transpose(array)
print(trans)
print("\n\n",trans.shape)

[[7 7]
 [9 7]
 [1 2]]


 (3, 2)


In [140]:
# OR
trans2 = array.T
print(trans2)
print("\n\n",trans2.shape)

[[7 7]
 [9 7]
 [1 2]]


 (3, 2)


In [141]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 5 7]
 [3 1 1]]
(2, 3)


In [146]:
b = a.reshape(6,1)
print(b)
print(b.shape)

[[4]
 [5]
 [7]
 [3]
 [1]
 [1]]
(6, 1)


In [16]:
x = np.random.randn(10)
print(x)

[ 0.54984906 -1.06299035 -0.00671682  0.40260612  0.28968252  0.22947003
 -0.43636328 -0.79580134  0.67224762  1.2284336 ]


In [15]:
x = np.random.randn(9999999)
print(np.mean(x))

-0.00014190331591892866


In [18]:
np.random.seed(123)
mat1 = np.random.randint(1,12,9).reshape(3,3)
mat2 = np.random.randint(5,15,9).reshape(3,3)
mat1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [19]:
mat2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [28]:
# Average time ke liye
%timeit [i**2 for i in range(1,11)]

3.11 µs ± 241 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
import numpy as np

In [29]:
%timeit np.arange(1,11)**2               #Compare average time taken. Numpy arrays are faster than List

1.39 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [25]:
# Poore cell ka average time ke liye
%%timeit
l = []
for i in range(10):
    l.append(i**2)
print(l)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


# Horizontal and Vertical Stacking

In [40]:
mat1 = np.random.randint(1,20,(3,3))
mat2 = np.random.randint(20,40,(3,3))
h = np.hstack((mat1,mat2))
v = np.vstack((mat1,mat2))

In [41]:
mat1

array([[18, 15, 11],
       [ 4,  4,  2],
       [16, 14, 17]])

In [42]:
mat2

array([[25, 28, 33],
       [34, 35, 28],
       [33, 37, 20]])

In [43]:
h # Horizontal Stacking

array([[18, 15, 11, 25, 28, 33],
       [ 4,  4,  2, 34, 35, 28],
       [16, 14, 17, 33, 37, 20]])

In [44]:
v  # Vertical Stacking

array([[18, 15, 11],
       [ 4,  4,  2],
       [16, 14, 17],
       [25, 28, 33],
       [34, 35, 28],
       [33, 37, 20]])

# Indexing and Slicing of 2-D Matrix

In [45]:
import numpy as np

In [53]:
np.random.seed(1334)
matrix = np.random.randint(1,10,(3,3))
matrix

array([[4, 7, 9],
       [3, 1, 5],
       [9, 6, 9]])

In [55]:
# Indexing using double bracket Notation:
matrix[0][1]

7

In [57]:
matrix[1][2]

5

In [56]:
# Indexing using single bracket Notation: (Recommended)
matrix[0,1]

7

In [58]:
matrix[1,2]

5

In [59]:
# Slicing using single bracket notation:
matrix

array([[4, 7, 9],
       [3, 1, 5],
       [9, 6, 9]])

In [62]:
matrix[:2, :2]

array([[4, 7],
       [3, 1]])

In [63]:
matrix[:3, :2]

array([[4, 7],
       [3, 1],
       [9, 6]])

In [64]:
matrix[:2,:3]

array([[4, 7, 9],
       [3, 1, 5]])

In [71]:
matrix[1:4, 1:4]

array([[1, 5],
       [6, 9]])

In [72]:
np.random.seed(123)
mat3 = np.random.randint(1,101,(5,5))
mat3

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [73]:
mat3[1:4,2:]

array([[98, 97, 48],
       [47, 97, 26],
       [37, 97, 81]])

In [74]:
mat3[1:5,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97],
       [50, 56, 68]])

# Numpy Axis

In [75]:
np.random.seed(1345)
matrix = np.random.randint(1,20,(3,3))
matrix

array([[ 3,  7,  6],
       [ 1, 16,  3],
       [ 7,  2, 17]])

In [76]:
np.min(matrix,axis = 1)

array([3, 1, 2])

In [78]:
np.max(matrix,axis = 1)

array([ 7, 16, 17])

In [77]:
np.max(matrix,axis = 0)

array([ 7, 16, 17])

In [79]:
np.min(matrix,axis = 0)

array([1, 2, 3])

In [80]:
np.sum(matrix, axis = 1)

array([16, 20, 26])

In [81]:
np.sum(matrix, axis=0)

array([11, 25, 26])

In [84]:
np.prod(matrix, axis=1)

array([126,  48, 238])

In [83]:
np.cumsum(matrix)   # Cummulative Sum

array([ 3, 10, 16, 17, 33, 36, 43, 45, 62], dtype=int32)